language: scala
sudo: false
jdk:
  - oraclejdk8
scala:
   - 2.10.7
   - 2.11.12
   - 2.12.7
   - 2.13.0-M5
branches:
  only:
    - master
    - develop
    - /^release\/.*$/
    - /^feature\/.*$/
script:
  - sbt ++$TRAVIS_SCALA_VERSION test doc
